### ISSUE TITLE
Russie

### ISSUE THREAD

**Issue by svelhinh** [jgigault/42MapGenerator#1]
La russie ne fonctionne pas.

**Comment by jgigault** [comment]
Salut @svelhinh

En effet le serveur du NOAA renvoit une erreur:
`msWCSGetCoverage(): WCS server error. Raster size out of range, width and height of resulting coverage must be no more than MAXSIZE=5000.`

Je vais ajouter une gestion d'erreur :-)

Merci

**Comment by jgigault** [comment]
Issue fixed on released v2 of 42MapGenerator
