### ISSUE TITLE
Dèrniere ligne génerée: fausse

### ISSUE THREAD

**Issue by NPWR** [jgigault/42MapGenerator#5]
Salut !
Tout d'abord merci pour ton travail, c'est de la bombe !

Bug: 
    -La derniere ligne generee est remplie de valeur fausses
Reproduce:
    -Find City
    -Paris
    -XXL
    -Keep Data

C'est un exemple, ca me l'a fait pour d'autres villes egalement. Bon debug ;)

**Comment by jgigault** [comment]
Hello @NPWR 
Merci de m'avoir prévenu !
J'ai fixé :-)
