### ISSUE TITLE
Map corrompus avant conversion ?

### ISSUE THREAD

**Issue by Hohenfels** [jgigault/42MapGenerator#7]
Pas mal des maps sont corrompu une fois generée depuis le mapgen

**Comment by jgigault** [comment]
Hello. Peux-tu me donner un exemple concret que tu as rencontré stp ?
Merci :)

**Comment by Hohenfels** [comment]
https://www.noelshack.com/2017-11-1489675503-screen-shot-2017-03-16-at-3-44-30-pm.png

Voila un exemple avec NOAA en provider, en ayant chercher la France, generé en taille M et ocean plat.
Y'en a beaucoup d'autre et j'ai remarque que ce sont uniquement les provider autre que IGN, enfin j'ai l'impression !
