### ISSUE TITLE
Merci de casser mon projet :)

### ISSUE THREAD

**Issue by Tomotomo-chan** [jgigault/42MapGenerator#8]
Bonjour,
(Je risque d'avoir quelque peu de mal à garder mon calme.)
Il serait surement judicieux de vérifier lors de l'update que le git à update est bien celui du 42 generator. Je t'explique: j'ai téléchargé le repo (donc pas clone) et mis dans mes maps sur MON repo de FdF.
Je lance le generator et il demande pour les maj, ok innocemment, je lance la maj.
Mais du coup c'est MON repo qu'il met à jour, j'imagine, et du coup MERCI adieu tous mes commits et tout mon travail de la matinée.
Donc voilà si c'est, comme je le suppose, ton script qui met à jour le repo, ce pourrait être une bonne piste de vérifier avant ça que c'est bien le 42generator, le repo en question...
My bad si le problème vient d'ailleurs, mais vraiment c'est juste apres avoir lancé le map generator et les updates que tout s'est envolé donc si tu as la possibilité de te pencher sur la question et d'éviter que ça se reproduise ce serait cool.
Merci.
Cordialement

**Comment by jgigault** [comment]
Salut @Tomotomo-chan 
Je suis navré de ce qui t'es arrivé car en effet il n'y a pas de vérification de ce côté-là.
Je ne veux pas empêcher la possibilité de forker le repo et d'en changer le nom, mais cela dit il pourrait y avoir un avertissement si le repo n'est pas l'original, sans pour autant refuser l'update.
La mise à jour se basant sur l'utilitaire git, il n'a pas été pensé pour un download et d'ailleurs le Readme ne propose pas de solutions alternative au "clonage" du repo.
Merci de m'avoir fait ton retour, et encore navré que tu aies perdu tes commits.
Jean-Michel

**Comment by Tomotomo-chan** [comment]
Désolée pour le ton sans doute agressif mais c'est vraiment horripilant comme situation ^^'
Je comprends par rapport à la possibilité de fork/changer le nom du repo. Un avertissement pourrait être pas mal...
My bad de ne pas avoir suivi le README à la lettre.
A part ça ton script est vraiment pratique, c'est du bon travail.

**Comment by jgigault** [comment]
Haha pas de soucis, et je comprend ton ressenti !
Je ferai une mise à jour promis
Merci, et je serais curieux d'avoir quelques screenshots de ton FdF. Quand tu l'auras réparé... :-)

**Comment by jgigault** [comment]
Fixed with #9
